spring:
  profile.active: dev, test, prod
  datasource:
    url: {utl-baseDeDatos}
    username: {Usuario}
    password: {Password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: 123456
